// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdaitvyFJHqo5_m7B--rFFv-sqMqKuhyg',
    appId: '1:139880518314:web:1130600d2e1227406df6d3',
    messagingSenderId: '139880518314',
    projectId: 'hudumaapp-7b493',
    authDomain: 'hudumaapp-7b493.firebaseapp.com',
    storageBucket: 'hudumaapp-7b493.firebasestorage.app',
    measurementId: 'G-WTQE012VRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQytxp_lfSltVsV-fqMtfJZfiTnx43WyE',
    appId: '1:139880518314:android:d908bef03844ae4c6df6d3',
    messagingSenderId: '139880518314',
    projectId: 'hudumaapp-7b493',
    storageBucket: 'hudumaapp-7b493.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkORxjlBVfRKFgs8GBFNFkbFvrYH52qGg',
    appId: '1:139880518314:ios:140337f3a2ad6df86df6d3',
    messagingSenderId: '139880518314',
    projectId: 'hudumaapp-7b493',
    storageBucket: 'hudumaapp-7b493.firebasestorage.app',
    androidClientId: '139880518314-k6arbath02d2lebv7muqbp1jl30fu3b2.apps.googleusercontent.com',
    iosClientId: '139880518314-puq39v2nr187l3b77g55c2g3n6gk4nb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

}